# 安装必备软件
---
- name: 准备nodejs环境
  hosts: "{{ host }}"
  tags: [init, nodejs, pm2]
  run_once: yes
  tasks:
    - name: 安装包
      dnf:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - nodejs
          - npm
- name: 准备golang
  hosts: "{{ host }}"
  tags: [golang, init]
  tasks:
    - name: 下载安装包
      get_url:
        url: https://golang.google.cn/dl/go{{ go_version }}.linux-amd64.tar.gz
        dest: /root/golang{{ go_version }}.tar.gz
        mode: "0440"
    - name: 删除旧的安装
      ansible.builtin.file:
        path: /usr/local/go
        state: absent
      when:
    - name: 解压安装
      ansible.builtin.unarchive:
        remote_src: yes
        src: /root/golang{{ go_version }}.tar.gz
        dest: /usr/local
- name: nodejs全局包
  hosts: "{{ host }}"
  tasks:
    - name: 安装pm2
      community.general.npm:
        name: pm2
        global: yes
      tags:
        - pm2
- name: 容器环境
  hosts: "{{ host }}"
  tags: [init, podman]
  tasks:
    - name: 开发环境
      dnf:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - podman
          - podman-docker
          - podman-compose
- name: java
  hosts: "{{ host }}"
  tags: [jdk, init]
  tasks:
    - name: 安装
      dnf:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - java-{{ jdk_version }}-openjdk
- name: 测试
  import_playbook: test.playbook.yaml
