# 安装必备软件
---
- name: nodes
  import_playbook: software/nodejs.yml
- name: 准备golang
  import_playbook: software/golang.yml
- name: 容器环境
  import_playbook: software/podman.yml
- name: java
  import_playbook: software/java.yml