- name: 版本检查
  vars_files:
    - var.json
  hosts: "{{ host }}"
  tags: [test]
  tasks:
    - ansible.builtin.shell:
        cmd: go version
      environment:
        PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
      register: command_output
      tags: [golang]
    - ansible.builtin.debug: var=command_output.stdout_lines verbosity=0
      tags: [golang]
    - ansible.builtin.shell: |
        node --version
        npm --version
      register: command_output
      tags: [nodejs]
    - ansible.builtin.debug: var=command_output.stdout_lines verbosity=0
      tags: [nodejs]
    - ansible.builtin.shell: |
        podman --version
      register: command_output
      tags: [podman]
    - ansible.builtin.debug: var=command_output.stdout_lines verbosity=0
      tags: [podman]
    - ansible.builtin.shell: |
        java --version
      register: command_output
      tags: [jdk]
    - ansible.builtin.debug: var=command_output.stdout_lines verbosity=0
      tags: [jdk]
