- name: 准备nodejs环境
  hosts: "{{ host }}"
  become: yes
  become_user: root
  tasks:
    - name: 下载包
      tags: download
      get_url:
        url: "https://nodejs.org/dist/{{node_version}}/node-{{node_version}}-linux-x64.tar.xz"
        dest: "/tmp/node-{{ node_version }}.tar.gz"
        mode: "0440"
        # https://nodejs.org/dist/v16.15.0/node-v16.15.0-linux-x64.tar.xz
    - name: 解压安装
      tags: install
      ansible.builtin.unarchive:
        remote_src: yes
        src: "/tmp/node-{{ node_version }}.tar.gz"
        dest: /usr/local/lib/
    - name: 必备包
      npm:
        name: "{{item}}"
        global: yes
        registry: https://registry.npmmirror.com
      loop:
        - pm2
      environment:
        PATH: /usr/local/lib/node-{{ node_version }}-linux-x64/bin/:{{ ansible_env.PATH }}
    - name: 配置环境变量
      tags: env
      file:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        state: link
      loop:
        - src: /usr/local/lib/node-{{ node_version }}-linux-x64/bin/node
          dest: /usr/bin/node
        - src: /usr/local/lib/node-{{ node_version }}-linux-x64/bin/npm
          dest: /usr/bin/npm
        - src: /usr/local/lib/node-{{ node_version }}-linux-x64/bin/pm2
          dest: /usr/bin/pm2
    - ansible.builtin.shell: |
        node --version
        npm --version
        pm2 --version
      register: command_output
    - ansible.builtin.debug: var=command_output.stdout_lines verbosity=0
